!!ARBfp1.0
# ARB_fragment_program generated by NVIDIA Cg compiler
# cgc version 1.2.0310 NDA Release, build date Nov  3 2003  16:18:32
# command line args: -profile arbfp1
#vendor NVIDIA Corporation
#version 1.0.02
#profile arbfp1
#program main
#semantic main.texture : TEXTURE0
#semantic main.normalMap : TEXTURE1
#var sampler2D texture :  : texunit 0 : 0 : 1
#var sampler2D normalMap :  : texunit 1 : 1 : 1
#var float2 pin.texCoord : $vin.TEXCOORD0 : TEX0 : 2 : 1
#var float3 pin.light : $vin.TEXCOORD1 : TEX1 : 2 : 1
#var float3 pin.eye : $vin.TEXCOORD2 : TEX2 : 2 : 1
#var float4 main : $vout.COLOR0 : COL : -1 : 1
PARAM c0 = {1, 1, 0.85000002, 2};
PARAM c1 = {0, 0, 0.15000001, 0.039999999};
PARAM c2 = {0.5, 0.5, 0.5, 0};
TEMP R0;
TEMP R1;
TEMP R2;
TEX R0.w, fragment.texcoord[0], texture[1], 2D;
ADD R0.x, R0.w, -c2.x;
MUL R0.x, R0.x, c1.w;
DP3 R0.y, fragment.texcoord[2], fragment.texcoord[2];
RSQ R0.y, R0.y;
MUL R1.xy, R0.y, fragment.texcoord[2];
MOV R2.y, R1.x;
MOV R2.x, -R1.y;
MAD R2.xy, R0.x, R2, fragment.texcoord[0];
TEX R0.xyz, R2, texture[1], 2D;
TEX R1, R2, texture[0], 2D;
ADD R0.xyz, R0, -c2;
MUL R0.xyz, R0, c0.w;
MOV R2.z, R0.z;
MOV R2.y, -R0.x;
MOV R2.x, -R0.y;
DP3 R0.x, fragment.texcoord[1], fragment.texcoord[1];
RSQ R0.x, R0.x;
MUL R0.xyz, R0.x, fragment.texcoord[1];
DP3 R0.x, R2, R0;
MAX R0.x, R0.x, c1.x;
MOV R2.xyz, c1;
MAD R2.xyz, c0, R0.x, R2;
MUL R2.xyz, R2, R1;
MOV R1.xyz, R2;
MOV result.color, R1;
END
# 26 instructions, 3 R-regs, 0 H-regs.
# End of program
